### PR TITLE
Fix Profile Picture Display for Users without Profile Pictures #532

### PR DESCRIPTION
**Pull request by ishant005**
Issue: #532

**Description**-Fix Profile Picture Display for Users without Profile Pictures 

What is the change?
Added dummy Picture for users without Profile Pictures

Is Development Tested?
 - [x]   Yes
 - [ ] No
 

Before / After Change Screenshots
Before :
Screenshot (54)

After :
Screenshot (53)

Test Coverage-
Screenshot (55)

Video--
https://github.com/Real-Dev-Squad/website-dashboard/assets/91171097/077bff33-e566-4bd9-907f-2b0b6060e6d3

### CODE REVIEW

**Comment by ajoykumardas12** [comment]
Please mention issue ticket too.

**Comment by ishant005** [comment]
> Please mention issue ticket too.

**Review by Achintya-Chatterjee — COMMENTED** [review]
Add a working video proof

**Review by ajoykumardas12 — APPROVED** [review]

**Review by Achintya-Chatterjee — COMMENTED** [review]
@ishant005 get it reviewed by at least one member

**Review by sahsisunny — APPROVED** [review]
LGTM :+1

**Review by Achintya-Chatterjee — APPROVED** [review]
LGTM

**Pull request merged**
