### PR TITLE
Enhancement: Make the /identity-service-logs UI infinite scroll

### LINKED ISSUE #827: Enhancement: Make the /identity-service-logs UI infinite scroll
### Issue Description
The identity-service-logs/ page currently shows limited no of logs and the next logs can be only accessed by next button. 

### Expected Behavior
The page should have infinite scroll and all the logs are displayed there itself.

### Current Behavior
There is a next button below which has to be clicked to access new logs.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. go to https://dashboard.realdevsquad.com/identity-service-logs/
2. scroll below and then click on the next button

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [x] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by listiclehub1**
Date: 20 Sep 2024

Developer Name: Utkarsh Bansal

---

## Issue Ticket Number
- Closes #827 

## Description
Removed the previously next and prev button and added Intersection Observer so that when you reach the bottom of the page the new data is automatically fetched from api and added.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>

<summary>Screenshot 1</summary>
Before the changes

https://github.com/user-attachments/assets/a8de92e7-bd0b-41b9-9b1f-7fd52516dd78
</details>
<details>
<summary>Screenshot 2</summary>

After Changes

https://github.com/user-attachments/assets/515c22c8-8708-4de6-8f46-3ca0ff89f01b

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-09-20
</details>

### CODE REVIEW

**Review by iamitprakash — DISMISSED** [review]
why this is not inside feature flag

**Comment by iamitprakash** [comment]
@listiclehub1 I don't see FF in your screen recording URL

**Review by iamitprakash — CHANGES_REQUESTED** [review]
tests are failing

**Comment by listiclehub1** [comment]
> @listiclehub1 I don't see FF in your screen recording URL

@iamitprakash I have updated the screen recording with feature flag.

**Comment by listiclehub1** [comment]
> tests are failing

I checked after re running the tests are passing.

https://github.com/user-attachments/assets/70d9dbc6-6549-4055-b8e6-b517c5840ebc

(ps - Have increased the video speed.)

**Review by iamitprakash — APPROVED** [review]

**Pull request merged**
