### PR TITLE
feat: added sync onboarding 31 days plus users button

### PR DESCRIPTION
**Pull request by AnjaliDeshwani**
**Issue** - https://github.com/Real-Dev-Squad/website-dashboard/issues/539

**Changes** - A button is added to the dashboard site for SUPERUSER to run the API and sync the "group-onboarding-31d+" users.

**Demo** -
image

https://github.com/Real-Dev-Squad/website-dashboard/assets/30263070/aa46d6a0-600d-4e7e-868a-4ec7353235c0

**Test Coverage :**

image

### CODE REVIEW

**Review by iamitprakash — CHANGES_REQUESTED** [review]
button looks odd than others

**Review by iamitprakash — APPROVED** [review]

**Review by iamitprakash — CHANGES_REQUESTED** [review]
Screenshot 2023-10-06 at 23 13 23
Please change time format as others. SS is from Prod

**Comment by AnjaliDeshwani** [comment]
> Screenshot 2023-10-06 at 23 13 23 Please change time format as others. SS is from Prod

I checked in code all of these buttons are using the same below function to get the time. I think "Date().toLocaleString()" shows the time depending on the browser and the user's locale settings
 
 `function getCurrentTimestamp() {
  return new Date().toLocaleString();
}`

**Review by iamitprakash — APPROVED** [review]

**Review by anishpawaskar — APPROVED** [review]
LGTM🚀

**Review by Achintya-Chatterjee — APPROVED** [review]

**Pull request merged**
