### PR TITLE
Handle Extension Request Card on Status Update

### PR DESCRIPTION
**Pull request by Aryex82**
Issue : #430  

### Why the change?
Currently the new extension request cards does not provide any feedback to the user when the status is changed. 

### What is the change?

- It handles the user flow when the user clicks on either the APPROVE or DENY button on the extension requests
- It adds a new spinner Element.

### Updated flow
- When user a clicks on either APPROVE or DENY the card will display a loader indicating there's an ongoing network call.
- If the network call is **successful** the card will transition out of the viewport and there will be one less card on the page.
- If the network call is **unsuccessful** the card will change its background color to red for the duration of 1s and it will remain on the page.

### Note to Reviewers:
- The feature is under a feature flag. To access, please use `?dev=true` query param.

### Test stats
Screenshot 2023-08-15 at 2 32 55 PM

### \*Dev Tested?

- [x] Yes
- [ ] No

### Backend Changes
- [ ] Yes
- [x] No

### After Change video: 

https://github.com/Real-Dev-Squad/website-dashboard/assets/98796547/b86f6821-2d97-41b1-ad83-c4b2dd61f2ea

Note: Api response were mocked to capture the video.

### CODE REVIEW

**Comment by vinit717** [comment]
image

**Comment by Aryex82** [comment]
> image

This is not within the scope of this PR as it only addresses the status update flow. Can you please explain the reason behind this so that I can create a separate issue.

**Comment by vinit717** [comment]
Is this feature behind feature-flag?

**Comment by Aryex82** [comment]
> Is this feature behind feature-flag?

yes I have also mentioned this in description

**Review by prakashchoudhary07 — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]

**Review by shubhamsigdar1 — APPROVED** [review]

**Pull request merged**
