### PR TITLE
added onboarding option in filter

### PR DESCRIPTION
**Pull request by fakhruddinkw**
Added new option in filter for users in dashboard.

**SCREEN SHOT**
issue-image

after-adding

### CODE REVIEW

**Review by vinit717 — APPROVED** [review]

**Comment by sahsisunny** [comment]
> after-adding

Why Skilles are not showing in the filter(In the screenshot)?

**Comment by sahsisunny** [comment]
Also, add the test for your changes

**Review by sahsisunny — APPROVED** [review]

**Review by shubhamsigdar1 — COMMENTED** [review]
Hey @fakhruddinkw Can you please make one video
want to see that filtering works or not

**Comment by fakhruddinkw** [comment]
> Hey @fakhruddinkw Can you please make one video want to see that filtering works or not

When archive:

https://github.com/Real-Dev-Squad/website-dashboard/assets/85249044/5b1788e1-8c69-4413-afd0-71ca9098748e

When not archive: 

https://github.com/Real-Dev-Squad/website-dashboard/assets/85249044/3157f2e0-4d9e-4a22-b6a0-35276de8c1ee

**Review by shubhamsigdar1 — APPROVED** [review]

**Review by Pratiyushkumar — APPROVED** [review]
LGMT

**Pull request merged**
