### PR TITLE
Update index.html link buttton

### PR DESCRIPTION
**Pull request by c00kie123**
Change link button to Anchor Tag as requested in #285

### CODE REVIEW

**Comment by sahsisunny** [comment]
Learn the issue in detail please

**Comment by c00kie123** [comment]
Can I ask what is wrong?

**Comment by c00kie123** [comment]
Can I ask what is the error? I have checked my syntax again and I do not find any wrong closing tags

**Comment by sahsisunny** [comment]
@c00kie123 For the time being, I will fix this issue and if you want to work on any new issue, then join **Real Dev Squad's** Discord channel.

**Pull request closed without merging**
