### PR TITLE
Refactor task form #21

### PR DESCRIPTION
**Pull request by bhk31**
Before 
before

After
after

### CODE REVIEW

**Comment by bhk31** [comment]
This PR also has changes related to issue [24](https://github.com/Real-Dev-Squad/website-dashboard/issues/24).

**Review by whyDontI — CHANGES_REQUESTED** [review]
- @bhk31 Can you also make sure that the task data we are sending with POST request adheres to this [contract](https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/tasks#post-tasks)
- Make sure the date we send to the backend is an `epoch / Unix timestamp`

**Review by whyDontI — CHANGES_REQUESTED** [review]
Great work @bhk31,
Requesting some changes.
- Dates should be sent as epoch strings ( Right now they are being sent as numbers)
- Change `dev` to `feature`
- `assignedTo` should be `assignee`
- Send `dinero and neelam` in `completionAward and lossRate` fields
devtools-ss

**Review by whyDontI — APPROVED** [review]
Great work @bhk31 🥳

**Pull request merged**
