### PR TITLE
fix: add option to sync Idle and Active Users on syncUsersStatus button

### PR DESCRIPTION
**Pull request by anishpawaskar**
**Issue :-** https://github.com/Real-Dev-Squad/website-dashboard/issues/433

**What is change?**
- The superuser should be able to run two more API on synceUserStatus button and those API which are not
- Also change the button positioning

Before :-
Dashboard _ Real Dev Squad - Google Chrome 04-08-2023 12_37_03

After :-
New Tab - Google Chrome 04-08-2023 12_38_42

Running two API concurrently who are non-dependent to save time :-
Dashboard _ Real Dev Squad - Google Chrome 04-08-2023 12_40_05

Test Coverage :-

package json - website-dashboard - Visual Studio Code 07-08-2023 04_11_40 (2)

### CODE REVIEW

**Review by Pratiyushkumar — COMMENTED** [review]
can we also include test and test coverage pls

**Review by heyrandhir — APPROVED** [review]

**Review by heyrandhir — CHANGES_REQUESTED** [review]
Build is failing please check.

**Comment by anishpawaskar** [comment]
> Build is failing please check.

added prettier command changes now it's working

**Review by heyrandhir — APPROVED** [review]

**Review by Pratiyushkumar — APPROVED** [review]
LGTM

**Pull request merged**
