### PR TITLE
Fix status filter query param on applications page

### LINKED ISSUE #797: Fix status query param on applications page
### Issue Description

When a status filter is applied without clearing the existing status filter, a new query param is added in the URL with the same name and new status value.

### Expected Behavior

The status query param's value should be updated in the URL instead of adding a new status query param
For example: On selecting the rejected filter , URL = `/applications/?status=rejected`
On selecting the accepted filter, URL = `/applications/?status=accepted`
### Current Behavior

On selecting the rejected filter , URL = `/applications/?status=rejected`
On selected the accepted filter, URL = `/applications/?status=rejected&status=accepted`
And so on if we keep changing the status filter value without clearing it
### Screenshots

https://github.com/user-attachments/assets/1ff8be28-5d0f-41db-93bf-9e9c95ed0349

### Reproducibility
 - [X] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Go to the `/applications` page
2. Apply the rejected status filter.
3. Apply the accepted status filter.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [X] Medium
 - [ ] Low

### Checklist

- [X] I have read and followed the project's code of conduct.
- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.
- [X] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by samarpan1738**
Date: 28 Aug 2024

Developer Name: Samarpan Harit

---

## Issue Ticket Number

closes #797 
## Description

1. Before adding a query param in the URL, check if it already exists in the URL
2. If yes, then remove it
3. Add the query param to the URL
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [X] No

### Database Changes

- [ ] Yes
- [X] No

### Breaking Changes

- [ ] Yes
- [X] No

### Development Tested?

- [X] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/f55d2537-6116-43d2-9562-6432fdad3849

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Screenshot from 2024-08-28 19-23-14

</details>

### CODE REVIEW

**Comment by vinit717** [comment]
Can you also check the accept/reject button in different scenarios

**Comment by samarpan1738** [comment]
> Can you also check the accept/reject button in different scenarios

Pending Status - Both buttons are active
Accepted Status - Both buttons are disabled
Rejected Status
    - Reject button is disabled
    - Accept button is enabled
@vinit717

**Comment by samarpan1738** [comment]
> > Can you also check the accept/reject button in different scenarios
> 
> Pending Status - Both buttons are active Accepted Status - Both buttons are disabled Rejected Status - Reject button is disabled - Accept button is enabled @vinit717
> 
> @iamitprakash Can you please confirm if this is the expected behaviour?

As discussed with Ankush, 
1. Pending Status - Both buttons are active
2. Accepted Status - Remove both buttons and add a Accepted message in it's place 
3. Rejected Status - Remove both buttons and add a Rejected message in it's place

I'll create a new issue for this

**Review by vinit717 — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]

**Comment by iamitprakash** [comment]
@samarpan1738  do you want me to merge this PR

**Comment by samarpan1738** [comment]
> @samarpan1738 do you want me to merge this PR

yes

**Pull request merged**
