### PR TITLE
Successfully fix make create task button responsive #99 as per requirement

### PR DESCRIPTION
**Pull request by ShivamPali-2020**
Hi @aman7870 ,

I have fixed the active issue #99 as per requirement. Kindly review it. and let me know if require any other changes.

Screenshot (54)
### Added hover effect on create task button .
Screenshot (55)

### CODE REVIEW

**Comment by abhinav1590** [comment]
> @aman7870 can you help me here, why it's failing CI/build? I have done changes only in CSS file.

**Comment by ShivamPali-2020** [comment]
Screenshot (58)
@abhinav1590 
can you help me out in this error

**Comment by abhinav1590** [comment]
The error says `Code style issues found in the above file(s). Forgot to run Prettier?` , so how do we fix such errors ? **And can we please have this conversation in the discord channel, this will help others too**

**Comment by aman7870** [comment]
Issue still going will be fixed in this PR #101

**Pull request closed without merging**
