### PR TITLE
Show applied filter on applications page with delete option

### PR DESCRIPTION
**Pull request by ahsrah7**
Date: 23-09-2024

Developer Name: Harshavardhan

---

## Issue Ticket Number

https://github.com/Real-Dev-Squad/website-dashboard/issues/828
## Description

- Change the filter ui to
    - Show applied filter 
    - option to remove the applied filter
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/5f81342e-5ffe-4f19-a855-0a45f5388140

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

test_coverage

</details>

### CODE REVIEW

**Review by iamitprakash — CHANGES_REQUESTED** [review]
please put this under FF

**Comment by yesyash** [comment]
@ahsrah7 please add test cases for your changes

**Comment by ahsrah7** [comment]
> please put this under FF



> please put this under FF

@iamitprakash  I have added the feature flag. Please have a look.

**Comment by ahsrah7** [comment]
> @ahsrah7 please add test cases for your changes

@yesyash I have added the relevant test case. Please have a look.

**Review by iamitprakash — APPROVED** [review]

**Pull request merged**
